name: Build & Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, 'skip build')
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepare

      - name: Get release type
        id: get-release-type
        run: |
          if [[ "${{ contains(github.event.pull_request.title, 'minor') }}" == "true" ]]
          then
            echo "RELEASE_TYPE=minor" >> $GITHUB_OUTPUT
          elif [[ "${{ contains(github.event.pull_request.title, 'major') }}" == "true" ]]
          then
            echo "RELEASE_TYPE=major" >> $GITHUB_OUTPUT
          else
            echo "RELEASE_TYPE=patch" >> $GITHUB_OUTPUT
          fi

      - name: Publish
        shell: bash
        run: |
          git config --global user.email "jamie.livingstone1@outlook.com"
          git config --global user.name "JamieLivi (via GitHub Actions)"
          yarn release --ci ${{steps.get-release-type.outputs.RELEASE_TYPE}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
