name: Build & Publish

permissions: write-all
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.pull_request.merged == true) && !contains(github.event.pull_request.title, 'skip build') }} || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    env:
      NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepare

      - name: Get release type
        id: get-release-type
        run: |
          if [[ "${{ contains(github.event.pull_request.title, 'minor') }}" == "true" ]]
          then
            echo "RELEASE_TYPE=minor" >> $GITHUB_OUTPUT
          elif [[ "${{ contains(github.event.pull_request.title, 'major') }}" == "true" ]]
          then
            echo "RELEASE_TYPE=major" >> $GITHUB_OUTPUT
          else
            echo "RELEASE_TYPE=patch" >> $GITHUB_OUTPUT
          fi

      - name: Publish
        shell: bash
        run: |
          git config --global user.email "jamie.livingstone1@outlook.com"
          git config --global user.name "JamieLivi (via GitHub Actions)"
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_AUTH_TOKEN }}
          yarn release --ci ${{steps.get-release-type.outputs.RELEASE_TYPE}}
